# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# importing required libraries
from PyQt5 import QtCore, QtGui, QtWidgets
import os
from os import *
import sys
import time
import requests
import bs4
from bs4 import *
from requests import *
from bs4 import BeautifulSoup


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        global cases
        global deaths
        global reco
        # connect to the website
        myvar = requests.get("https://www.worldometers.info/coronavirus/")

        # getting source code of the website
        soup = BeautifulSoup(myvar.text, 'lxml')
        # Getting Cases, Deaths and Recoveries
        get_cases = soup.find_all('div', class_ = 'maincounter-number')

        # storing in a variable
        cases = get_cases[0].text
        deaths = get_cases[1].text
        reco = get_cases[2].text
        # printing them to test if this fails then the program will crash
        print("Cases: " + cases)
        print("Deaths: " + deaths)
        print("Recovered: " + reco)

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: #3c275c;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 771, 551))
        self.groupBox.setStyleSheet("background-color: #3c275c;")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(70, 80, 121, 51))
        self.label.setStyleSheet("color: white;\n"
"font-size: 25px;\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(620, 80, 121, 51))
        self.label_2.setStyleSheet("font-size: 25px;\n"
"color: red;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(310, 260, 131, 51))
        self.label_3.setStyleSheet("color: green;\n"
"font-size: 25px;")
        self.label_3.setObjectName("label_3")
        self.Cases_lbl = QtWidgets.QLabel(self.groupBox)
        self.Cases_lbl.setGeometry(QtCore.QRect(10, 150, 191, 51))
        self.Cases_lbl.setStyleSheet("background-color: white;\n"
"color: black;\n"
"font-size: 23px;\n"
"")
        self.Cases_lbl.setText(cases)
        self.Cases_lbl.setObjectName("Cases_lbl")
        self.Deaths_lbl = QtWidgets.QLabel(self.groupBox)
        self.Deaths_lbl.setGeometry(QtCore.QRect(570, 150, 191, 51))
        self.Deaths_lbl.setStyleSheet("color: red;\n"
"background-color: white;\n"
"font-size: 23px;")
        self.Deaths_lbl.setText(deaths)
        self.Deaths_lbl.setObjectName("Deaths_lbl")
        self.Recoveries_lbl = QtWidgets.QLabel(self.groupBox)
        self.Recoveries_lbl.setGeometry(QtCore.QRect(280, 320, 191, 51))
        self.Recoveries_lbl.setStyleSheet("font-size: 23px;\n"
"color: green;\n"
"background-color: white;")
        self.Recoveries_lbl.setText(reco)
        self.Recoveries_lbl.setObjectName("Recoveries_lbl")
        self.Info = QtWidgets.QLabel(self.groupBox)
        self.Info.setGeometry(QtCore.QRect(230, 510, 311, 31))
        self.Info.setStyleSheet("color: green;")
        self.Info.setObjectName("Info")
        self.Info_2 = QtWidgets.QLabel(self.centralwidget)
        self.Info_2.setGeometry(QtCore.QRect(300, 560, 191, 31))
        self.Info_2.setStyleSheet("color: green;")
        self.Info_2.setObjectName("Info_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WorldWide Covid-19 Cases"))
        self.groupBox.setTitle(_translate("MainWindow", "Covid Cases, Deaths and Recoveries worldwide"))
        self.label.setText(_translate("MainWindow", "Cases:"))
        self.label_2.setText(_translate("MainWindow", "Deaths:"))
        self.label_3.setText(_translate("MainWindow", "Recoveries:"))
        self.Info.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Info collected from: &quot;w</span><span style=\" font-weight:600;\">orldometer.info/coronavirus/&quot;</span></p></body></html>"))
        self.Info_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; text-decoration: underline;\">Project made by: SapphireKR</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
